### ISSUE TITLE
Hide everything except the intended page's name

### ISSUE THREAD

**Issue by YU000jp** [YU000jp/logseq-plugin-short-namespaces#24]
like this
`../../../Like`
`../Like`

_Originally posted by @rowsof in https://github.com/YU000jp/logseq-plugin-short-namespaces/discussions/8#discussioncomment-8194635_

- Vote:
  1. [rowsof](https://github.com/rowsof)
  1. [mcules](https://github.com/mcules)
  1. [ANNOARK](https://github.com/ANNOARK)

**Comment by YU000jp** [comment]
I released a new version. Please select `All levels` in the plugin settings.

**Comment by mcules** [comment]
> @rowsof @mcules @ANNOARK I released a new version. Please select `All levels` in the plugin settings.

Perfekt, thank you 👍

**Comment by rowsof** [comment]
Hooray! It really is perfect now. Thank you so much!

**Comment by ANNOARK** [comment]
Nice! Really thanks!
