### ISSUE TITLE
If the link wraps over a line in the sidebar, the hover text is squeezed into a tall, one-character wide column

### ISSUE THREAD

**Issue by kazerniel** [YU000jp/logseq-plugin-short-namespaces#29]
Seems to be caused by Logseq's default `word-break: break-word` set on blocks. It can be sorta solved by adding `word-break: normal` to the `::before` tooltip element, but that does cause the tooltip to hang off the edge of the sidebar (with a horizontal scrollbar appearing in the bottom).

Ideally the tooltip would be shifted left a bit to stay legible, but not sure how to achieve that with CSS from the top of my head 🤔

**Comment by YU000jp** [comment]
It's not perfect, but I've improved it to avoid the bug. I released a new version. Please update and try it.

**Comment by YU000jp** [comment]
I released a new version. Please try it.

**Comment by kazerniel** [comment]
Sorry, I stopped using Logseq in late March 😅
