### ISSUE TITLE
Feature: exclude compound tags #A/B/C

### ISSUE THREAD

**Issue by johnghill** [YU000jp/logseq-plugin-short-namespaces#33]
I often use compound tags as a way of leveraging the benefits of namespacing. I often end up with namespaced action tags, for example:  `#to/report`, `#to/action`, `#pg/draft` etc. Because the hierarchy is meaningful, I would prefer to display them in full. Could this plugin exclude compound tags of the form `#A/B/C` from namespace abbreviation?

**Comment by YU000jp** [comment]
Will adding the option "Do not omit hierarchy when page name contains '#'" solve the problem?

**Comment by johnghill** [comment]
> Will adding the option "Do not omit hierarchy when page name starts with '#'" solve the problem?

Thank you, I believe that it would.

**Comment by YU000jp** [comment]
I released a new version. Please try it.

**Comment by johnghill** [comment]
Feature fully implemented in release 1.8.0. Thank you very much!
